requires 'forks';
requires 'Text::CSV_XS';
requires 'DateTime', '1.50';
requires 'Moo';
requires 'JSON';
requires 'JSON::Parse';
requires 'JSON::XS';
requires 'Mojo::Util';
requires 'IO::Socket::SSL';
requires 'Text::Unidecode';